name: Merge Timing Data
description: Merge timing data from multiple shards using EMA (storage-agnostic)

inputs:
  existing-file:
    description: Path to existing timing data to merge with (optional)
    required: false
    default: ''
  new-files:
    description: Space-separated paths to new timing artifact files
    required: true
  output-file:
    description: Path to write merged timing data
    required: true
  alpha:
    description: EMA smoothing factor (0-1)
    required: false
    default: '0.3'
  prune-days:
    description: Remove entries older than N days
    required: false
    default: '30'
  level:
    description: Data level (file or test)
    required: false
    default: 'test'

outputs:
  test-count:
    description: Number of tests in merged data
    value: ${{ steps.merge.outputs.test-count }}
  success:
    description: Whether merge succeeded
    value: ${{ steps.merge.outputs.success }}

runs:
  using: composite
  steps:
    - name: Merge timing data
      id: merge
      shell: bash
      run: |
        # Check if any new files exist
        NEW_FILES="${{ inputs.new-files }}"
        VALID_FILES=""

        for file in $NEW_FILES; do
          # Handle glob patterns
          for expanded in $file; do
            if [ -f "$expanded" ]; then
              VALID_FILES="$VALID_FILES $expanded"
            fi
          done
        done

        if [ -z "$VALID_FILES" ]; then
          echo "::warning::No timing artifact files found"
          echo "test-count=0" >> $GITHUB_OUTPUT
          echo "success=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "Merging timing files:$VALID_FILES"

        # Build existing file argument
        EXISTING_ARG=""
        if [ -n "${{ inputs.existing-file }}" ] && [ -f "${{ inputs.existing-file }}" ]; then
          EXISTING_ARG="--existing ${{ inputs.existing-file }}"
          echo "Merging with existing data from ${{ inputs.existing-file }}"
        fi

        # Create output directory if needed
        mkdir -p "$(dirname "${{ inputs.output-file }}")"

        set +e
        playwright-orchestrator merge-timing \
          --new $VALID_FILES \
          --output "${{ inputs.output-file }}" \
          --alpha "${{ inputs.alpha }}" \
          --prune-days "${{ inputs.prune-days }}" \
          --level "${{ inputs.level }}" \
          $EXISTING_ARG
        EXIT_CODE=$?
        set -e

        if [ $EXIT_CODE -ne 0 ]; then
          echo "::warning::Failed to merge timing data"
          echo "test-count=0" >> $GITHUB_OUTPUT
          echo "success=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Get count from output
        if [ "${{ inputs.level }}" = "test" ]; then
          COUNT=$(jq '.tests | length' "${{ inputs.output-file }}" 2>/dev/null || echo "0")
        else
          COUNT=$(jq '.files | length' "${{ inputs.output-file }}" 2>/dev/null || echo "0")
        fi

        echo "test-count=$COUNT" >> $GITHUB_OUTPUT
        echo "success=true" >> $GITHUB_OUTPUT
        echo "Merged timing data has $COUNT entries"
