name: Setup
description: Setup mise and bun for the project

runs:
  using: composite
  steps:
    - name: Setup mise
      uses: jdx/mise-action@v2
      with:
        version: 2025.5.6

    - name: Setup bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: .tool-versions

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
