name: Filter Playwright Report
description: Remove orchestrator-skipped tests from a Playwright JSON report (storage-agnostic)

inputs:
  report-file:
    description: Path to Playwright JSON report file
    required: true
  output-file:
    description: Path to write filtered report (defaults to overwriting input)
    required: false

outputs:
  success:
    description: Whether filtering succeeded
    value: ${{ steps.filter.outputs.success }}

runs:
  using: composite
  steps:
    - name: Filter report
      id: filter
      shell: bash
      run: |
        if [ ! -f "${{ inputs.report-file }}" ]; then
          echo "::warning::Report file not found: ${{ inputs.report-file }}"
          echo "success=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        OUTPUT_ARG=""
        if [ -n "${{ inputs.output-file }}" ]; then
          OUTPUT_ARG="--output-file ${{ inputs.output-file }}"
        fi

        set +e
        playwright-orchestrator filter-report \
          --report-file "${{ inputs.report-file }}" \
          $OUTPUT_ARG \
          --verbose
        EXIT_CODE=$?
        set -e

        if [ $EXIT_CODE -ne 0 ]; then
          echo "::warning::Failed to filter report"
          echo "success=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "success=true" >> $GITHUB_OUTPUT
