name: Get Shard Test Arguments
description: Extract test arguments for a specific shard from orchestrate output

inputs:
  shard-files:
    description: JSON shard assignments from orchestrate action (shard-files output)
    required: true
  shard-index:
    description: Which shard to get (1-based)
    required: true
  shards:
    description: Total shard count (for native fallback)
    required: true

outputs:
  shard-file:
    description: Path to JSON file with test IDs for reporter-based filtering
    value: ${{ steps.parse.outputs.shard-file }}
  has-tests:
    description: Whether this shard has tests assigned
    value: ${{ steps.parse.outputs.has-tests }}
  test-count:
    description: Number of tests assigned to this shard
    value: ${{ steps.parse.outputs.test-count }}
  fallback-args:
    description: Native Playwright shard argument (--shard=N/M) for fallback
    value: ${{ steps.parse.outputs.fallback-args }}

runs:
  using: composite
  steps:
    - name: Parse shard assignment
      id: parse
      shell: bash
      run: |
        SHARD_FILES='${{ inputs.shard-files }}'
        SHARD_INDEX='${{ inputs.shard-index }}'
        TOTAL='${{ inputs.shards }}'

        # Always output fallback args
        echo "fallback-args=--shard=$SHARD_INDEX/$TOTAL" >> $GITHUB_OUTPUT

        # Check if we have valid shard files
        if [ -z "$SHARD_FILES" ] || [ "$SHARD_FILES" = "{}" ] || [ "$SHARD_FILES" = "null" ]; then
          echo "::notice::No orchestrator data, using native sharding for shard $SHARD_INDEX/$TOTAL"
          echo "has-tests=false" >> $GITHUB_OUTPUT
          echo "test-count=0" >> $GITHUB_OUTPUT
          echo "shard-file=" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Extract tests for this shard
        TESTS=$(echo "$SHARD_FILES" | jq -c ".\"$SHARD_INDEX\" // []")
        TEST_COUNT=$(echo "$TESTS" | jq 'length')

        if [ "$TEST_COUNT" = "0" ] || [ "$TEST_COUNT" = "null" ]; then
          echo "::notice::No tests assigned to shard $SHARD_INDEX, using native sharding"
          echo "has-tests=false" >> $GITHUB_OUTPUT
          echo "test-count=0" >> $GITHUB_OUTPUT
          echo "shard-file=" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "::notice::Shard $SHARD_INDEX has $TEST_COUNT tests"
        echo "has-tests=true" >> $GITHUB_OUTPUT
        echo "test-count=$TEST_COUNT" >> $GITHUB_OUTPUT

        # Write test IDs to JSON file for reporter-based filtering
        SHARD_FILE="$GITHUB_WORKSPACE/playwright-shard-$SHARD_INDEX.json"
        echo "$TESTS" > "$SHARD_FILE"
        echo "shard-file=$SHARD_FILE" >> $GITHUB_OUTPUT
