name: Orchestrate Playwright Tests
description: Assign tests to shards using historical timing data (storage-agnostic)

inputs:
  test-list:
    description: Path to JSON file with test list (from playwright --list --reporter=json). When provided, skips internal test discovery. This is the recommended approach for CI.
    required: false
    default: ''
  test-dir:
    description: Path to test directory (not required when using test-list)
    required: false
    default: ''
  shards:
    description: Total number of shards
    required: true
  timing-file:
    description: Path to timing data JSON file (optional)
    required: false
    default: ''
  level:
    description: Distribution level (file or test)
    required: false
    default: 'test'
  glob-pattern:
    description: Glob pattern for test files
    required: false
    default: '**/*.spec.ts'
  project:
    description: Playwright project name (only used when test-list is not provided)
    required: false
    default: ''
  config-dir:
    description: Directory where playwright.config.ts is located (only used when test-list is not provided)
    required: false
    default: ''

outputs:
  shard-files:
    description: JSON object with test/file assignments for all shards
    value: ${{ steps.assign.outputs.shard-files }}
  expected-durations:
    description: JSON object with expected durations for all shards
    value: ${{ steps.assign.outputs.expected-durations }}
  total-tests:
    description: Total number of tests/files
    value: ${{ steps.assign.outputs.total-tests }}
  is-optimal:
    description: Whether the distribution is optimal
    value: ${{ steps.assign.outputs.is-optimal }}
  use-orchestrator:
    description: Whether orchestration succeeded (use with get-shard action)
    value: ${{ steps.assign.outputs.use-orchestrator }}

runs:
  using: composite
  steps:
    - name: Assign tests to shards
      id: assign
      shell: bash
      run: |
        TOTAL_SHARDS="${{ inputs.shards }}"
        TEST_LIST="${{ inputs.test-list }}"
        PROJECT="${{ inputs.project }}"
        CONFIG_DIR="${{ inputs.config-dir }}"

        # Build command arguments
        CMD_ARGS=(
          --shards "$TOTAL_SHARDS"
          --level "${{ inputs.level }}"
          --output-format json
        )

        # Use test-list if provided (recommended for CI)
        if [ -n "$TEST_LIST" ] && [ -f "$TEST_LIST" ]; then
          CMD_ARGS+=(--test-list "$TEST_LIST")
          echo "Using pre-generated test list from $TEST_LIST"
        else
          # Fall back to test discovery (requires test-dir)
          if [ -z "${{ inputs.test-dir }}" ]; then
            echo "::error::Either test-list or test-dir must be provided"
            exit 1
          fi
          CMD_ARGS+=(--test-dir "${{ inputs.test-dir }}")
          CMD_ARGS+=(--glob-pattern "${{ inputs.glob-pattern }}")
          
          # Add project if specified
          if [ -n "$PROJECT" ]; then
            CMD_ARGS+=(--project "$PROJECT")
            echo "Using Playwright project: $PROJECT"
          fi

          # Add config-dir if specified
          if [ -n "$CONFIG_DIR" ]; then
            CMD_ARGS+=(--config-dir "$CONFIG_DIR")
            echo "Using Playwright config from: $CONFIG_DIR"
          fi
        fi

        # Add timing file if available
        if [ -n "${{ inputs.timing-file }}" ] && [ -f "${{ inputs.timing-file }}" ]; then
          CMD_ARGS+=(--timing-file "${{ inputs.timing-file }}")
          echo "Using timing data from ${{ inputs.timing-file }}"
        else
          echo "No timing data available, using estimation"
        fi

        # Try to run orchestrator
        set +e
        STDERR_FILE=$(mktemp)
        RESULT=$(playwright-orchestrator assign "${CMD_ARGS[@]}" 2>"$STDERR_FILE")
        EXIT_CODE=$?
        STDERR_OUTPUT=$(cat "$STDERR_FILE")
        rm -f "$STDERR_FILE"
        set -e

        # Show any warnings from orchestrator
        if [ -n "$STDERR_OUTPUT" ]; then
          echo "$STDERR_OUTPUT"
        fi

        # Check if orchestrator failed or returned invalid JSON
        if [ $EXIT_CODE -ne 0 ] || ! echo "$RESULT" | jq -e '.' > /dev/null 2>&1; then
          echo "::warning::Orchestrator failed (exit code $EXIT_CODE), falling back to native sharding"
          echo "::warning::Error output: $RESULT $STDERR_OUTPUT"
          
          echo "use-orchestrator=false" >> $GITHUB_OUTPUT
          echo "shard-files={}" >> $GITHUB_OUTPUT
          echo "expected-durations={}" >> $GITHUB_OUTPUT
          echo "total-tests=0" >> $GITHUB_OUTPUT
          echo "is-optimal=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Extract data from result
        IS_OPTIMAL=$(echo "$RESULT" | jq -r ".isOptimal // false")
        TOTAL_TESTS=$(echo "$RESULT" | jq -r ".totalTests // .totalFiles // 0")
        
        echo "use-orchestrator=true" >> $GITHUB_OUTPUT
        echo "shard-files=$(echo "$RESULT" | jq -c '.shards')" >> $GITHUB_OUTPUT
        echo "expected-durations=$(echo "$RESULT" | jq -c '.expectedDurations')" >> $GITHUB_OUTPUT
        echo "total-tests=$TOTAL_TESTS" >> $GITHUB_OUTPUT
        echo "is-optimal=$IS_OPTIMAL" >> $GITHUB_OUTPUT

        # Log summary
        echo "### Orchestrator Assignment" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Shard | Tests | Expected Duration |" >> $GITHUB_STEP_SUMMARY
        echo "|-------|-------|-------------------|" >> $GITHUB_STEP_SUMMARY
        for i in $(seq 1 $TOTAL_SHARDS); do
          COUNT=$(echo "$RESULT" | jq -r ".shards.\"$i\" | length")
          DURATION=$(echo "$RESULT" | jq -r ".expectedDurations.\"$i\"")
          DURATION_SEC=$((DURATION / 1000))
          echo "| $i | $COUNT | ${DURATION_SEC}s |" >> $GITHUB_STEP_SUMMARY
        done
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Total**: $TOTAL_TESTS tests, Optimal: $IS_OPTIMAL" >> $GITHUB_STEP_SUMMARY
