name: Orchestrate Playwright Tests
description: Assign tests to shards using historical timing data (storage-agnostic)

inputs:
  test-dir:
    description: Path to test directory
    required: true
  shards:
    description: Total number of shards
    required: true
  shard-index:
    description: Current shard index (1-based). Omit to output ALL shards.
    required: false
    default: ''
  timing-file:
    description: Path to timing data JSON file (optional)
    required: false
    default: ''
  level:
    description: Distribution level (file or test)
    required: false
    default: 'test'
  glob-pattern:
    description: Glob pattern for test files
    required: false
    default: '**/*.spec.ts'
  project:
    description: Playwright project name (for accurate test discovery with parameterized tests)
    required: false
    default: ''

outputs:
  # Single-shard outputs (when shard-index provided)
  grep-pattern:
    description: Grep pattern for this shard's tests
    value: ${{ steps.assign.outputs.grep-pattern }}
  test-count:
    description: Number of tests assigned to this shard
    value: ${{ steps.assign.outputs.test-count }}
  expected-duration:
    description: Expected duration in milliseconds
    value: ${{ steps.assign.outputs.expected-duration }}
  is-optimal:
    description: Whether the distribution is optimal
    value: ${{ steps.assign.outputs.is-optimal }}
  use-native-sharding:
    description: Whether to fallback to native Playwright sharding
    value: ${{ steps.assign.outputs.use-native-sharding }}
  shard-arg:
    description: Native shard argument (e.g., --shard=1/4)
    value: ${{ steps.assign.outputs.shard-arg }}
  # All-shards outputs (when shard-index omitted)
  shard-files:
    description: JSON object with file assignments for all shards
    value: ${{ steps.assign.outputs.shard-files }}
  grep-patterns:
    description: JSON object with grep patterns for all shards (test-level only)
    value: ${{ steps.assign.outputs.grep-patterns }}
  expected-durations:
    description: JSON object with expected durations for all shards
    value: ${{ steps.assign.outputs.expected-durations }}
  use-orchestrator:
    description: Whether orchestration succeeded (use with get-shard action)
    value: ${{ steps.assign.outputs.use-orchestrator }}

runs:
  using: composite
  steps:
    - name: Assign tests to shards
      id: assign
      shell: bash
      run: |
        SHARD_INDEX="${{ inputs.shard-index }}"
        TOTAL_SHARDS="${{ inputs.shards }}"
        PROJECT="${{ inputs.project }}"

        # Build command arguments as array to handle spaces correctly
        CMD_ARGS=(
          --test-dir "${{ inputs.test-dir }}"
          --shards "$TOTAL_SHARDS"
          --level "${{ inputs.level }}"
          --glob-pattern "${{ inputs.glob-pattern }}"
          --output-format json
        )

        # Add timing file if available
        if [ -n "${{ inputs.timing-file }}" ] && [ -f "${{ inputs.timing-file }}" ]; then
          CMD_ARGS+=(--timing-file "${{ inputs.timing-file }}")
          echo "Using timing data from ${{ inputs.timing-file }}"
        else
          echo "No timing data available, using estimation"
        fi

        # Add project if specified
        if [ -n "$PROJECT" ]; then
          CMD_ARGS+=(--project "$PROJECT")
          echo "Using Playwright project: $PROJECT"
        fi

        # Try to run orchestrator
        set +e
        RESULT=$(playwright-orchestrator assign "${CMD_ARGS[@]}" 2>&1)
        EXIT_CODE=$?
        set -e

        # Check if orchestrator failed or returned invalid JSON
        if [ $EXIT_CODE -ne 0 ] || ! echo "$RESULT" | jq -e '.' > /dev/null 2>&1; then
          echo "::warning::Orchestrator failed (exit code $EXIT_CODE), falling back to native sharding"
          echo "::warning::Error output: $RESULT"
          
          # All-shards outputs (for get-shard action)
          echo "use-orchestrator=false" >> $GITHUB_OUTPUT
          echo "shard-files={}" >> $GITHUB_OUTPUT
          echo "grep-patterns={}" >> $GITHUB_OUTPUT
          echo "expected-durations={}" >> $GITHUB_OUTPUT
          
          # Single-shard outputs (legacy)
          if [ -n "$SHARD_INDEX" ]; then
            echo "use-native-sharding=true" >> $GITHUB_OUTPUT
            echo "shard-arg=--shard=$SHARD_INDEX/$TOTAL_SHARDS" >> $GITHUB_OUTPUT
            echo "grep-pattern=" >> $GITHUB_OUTPUT
            echo "test-count=0" >> $GITHUB_OUTPUT
            echo "expected-duration=0" >> $GITHUB_OUTPUT
            echo "is-optimal=false" >> $GITHUB_OUTPUT
          fi
          exit 0
        fi

        # Extract common data
        IS_OPTIMAL=$(echo "$RESULT" | jq -r ".isOptimal // false")
        
        # All-shards outputs (for get-shard action)
        echo "use-orchestrator=true" >> $GITHUB_OUTPUT
        echo "shard-files=$(echo "$RESULT" | jq -c '.shards')" >> $GITHUB_OUTPUT
        echo "grep-patterns=$(echo "$RESULT" | jq -c '.grepPatterns // {}')" >> $GITHUB_OUTPUT
        echo "expected-durations=$(echo "$RESULT" | jq -c '.expectedDurations')" >> $GITHUB_OUTPUT

        # If shard-index provided, also output single-shard data (legacy mode)
        if [ -n "$SHARD_INDEX" ]; then
          GREP_PATTERN=$(echo "$RESULT" | jq -r ".grepPatterns[\"$SHARD_INDEX\"] // .grepPatterns[$SHARD_INDEX] // \"\"")
          TEST_COUNT=$(echo "$RESULT" | jq -r "(.shards[\"$SHARD_INDEX\"] // .shards[$SHARD_INDEX]) | length // 0")
          EXPECTED_DURATION=$(echo "$RESULT" | jq -r ".expectedDurations[\"$SHARD_INDEX\"] // .expectedDurations[$SHARD_INDEX] // 0")

          # Check if shard is empty (fallback to native)
          if [ -z "$GREP_PATTERN" ] || [ "$TEST_COUNT" = "0" ]; then
            echo "::notice::No tests assigned to shard $SHARD_INDEX, using native sharding"
            echo "use-native-sharding=true" >> $GITHUB_OUTPUT
            echo "shard-arg=--shard=$SHARD_INDEX/$TOTAL_SHARDS" >> $GITHUB_OUTPUT
          else
            echo "use-native-sharding=false" >> $GITHUB_OUTPUT
            echo "shard-arg=" >> $GITHUB_OUTPUT
          fi

          echo "grep-pattern=$GREP_PATTERN" >> $GITHUB_OUTPUT
          echo "test-count=$TEST_COUNT" >> $GITHUB_OUTPUT
          echo "expected-duration=$EXPECTED_DURATION" >> $GITHUB_OUTPUT
          echo "is-optimal=$IS_OPTIMAL" >> $GITHUB_OUTPUT

          echo "Assigned $TEST_COUNT tests to shard $SHARD_INDEX (expected: ${EXPECTED_DURATION}ms, optimal: $IS_OPTIMAL)"
        else
          echo "is-optimal=$IS_OPTIMAL" >> $GITHUB_OUTPUT
          
          # Log summary
          echo "### Orchestrator Assignment" >> $GITHUB_STEP_SUMMARY
          for i in $(seq 1 $TOTAL_SHARDS); do
            FILES=$(echo "$RESULT" | jq -r ".shards.\"$i\" | length")
            DURATION=$(echo "$RESULT" | jq -r ".expectedDurations.\"$i\"")
            echo "- **Shard $i**: $FILES files (~$((DURATION / 1000))s)" >> $GITHUB_STEP_SUMMARY
          done
        fi
