name: Orchestrate Playwright Tests
description: Assign tests to shards using historical timing data (storage-agnostic)

inputs:
  test-dir:
    description: Path to test directory
    required: true
  shards:
    description: Total number of shards
    required: true
  shard-index:
    description: Current shard index (1-based)
    required: true
  timing-file:
    description: Path to timing data JSON file (optional)
    required: false
    default: ''
  level:
    description: Distribution level (file or test)
    required: false
    default: 'test'
  glob-pattern:
    description: Glob pattern for test files
    required: false
    default: '**/*.spec.ts'

outputs:
  grep-pattern:
    description: Grep pattern for this shard's tests
    value: ${{ steps.assign.outputs.grep-pattern }}
  test-count:
    description: Number of tests assigned to this shard
    value: ${{ steps.assign.outputs.test-count }}
  expected-duration:
    description: Expected duration in milliseconds
    value: ${{ steps.assign.outputs.expected-duration }}
  is-optimal:
    description: Whether the distribution is optimal
    value: ${{ steps.assign.outputs.is-optimal }}
  use-native-sharding:
    description: Whether to fallback to native Playwright sharding
    value: ${{ steps.assign.outputs.use-native-sharding }}
  shard-arg:
    description: Native shard argument (e.g., --shard=1/4)
    value: ${{ steps.assign.outputs.shard-arg }}

runs:
  using: composite
  steps:
    - name: Assign tests to shard
      id: assign
      shell: bash
      run: |
        # Build timing-file argument
        TIMING_ARG=""
        if [ -n "${{ inputs.timing-file }}" ] && [ -f "${{ inputs.timing-file }}" ]; then
          TIMING_ARG="--timing-file ${{ inputs.timing-file }}"
          echo "Using timing data from ${{ inputs.timing-file }}"
        else
          echo "No timing data available, using estimation"
        fi

        # Try to run orchestrator, fallback to native sharding on failure
        set +e
        RESULT=$(playwright-orchestrator assign \
          --test-dir "${{ inputs.test-dir }}" \
          --shards "${{ inputs.shards }}" \
          --level "${{ inputs.level }}" \
          --glob-pattern "${{ inputs.glob-pattern }}" \
          --output-format json \
          $TIMING_ARG 2>&1)
        EXIT_CODE=$?
        set -e

        SHARD_INDEX="${{ inputs.shard-index }}"
        TOTAL_SHARDS="${{ inputs.shards }}"

        # Check if orchestrator failed
        if [ $EXIT_CODE -ne 0 ]; then
          echo "::warning::Orchestrator failed (exit code $EXIT_CODE), falling back to native sharding"
          echo "::warning::Error output: $RESULT"
          echo "use-native-sharding=true" >> $GITHUB_OUTPUT
          echo "shard-arg=--shard=$SHARD_INDEX/$TOTAL_SHARDS" >> $GITHUB_OUTPUT
          echo "grep-pattern=" >> $GITHUB_OUTPUT
          echo "test-count=0" >> $GITHUB_OUTPUT
          echo "expected-duration=0" >> $GITHUB_OUTPUT
          echo "is-optimal=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Parse result
        GREP_PATTERN=$(echo "$RESULT" | jq -r ".grepPatterns[\"$SHARD_INDEX\"] // .grepPatterns[$SHARD_INDEX] // \"\"")
        TEST_COUNT=$(echo "$RESULT" | jq -r "(.shards[\"$SHARD_INDEX\"] // .shards[$SHARD_INDEX]) | length // 0")
        EXPECTED_DURATION=$(echo "$RESULT" | jq -r ".expectedDurations[\"$SHARD_INDEX\"] // .expectedDurations[$SHARD_INDEX] // 0")
        IS_OPTIMAL=$(echo "$RESULT" | jq -r ".isOptimal // false")

        # Check if shard is empty (fallback to native)
        if [ -z "$GREP_PATTERN" ] || [ "$TEST_COUNT" = "0" ]; then
          echo "::notice::No tests assigned to shard $SHARD_INDEX, using native sharding"
          echo "use-native-sharding=true" >> $GITHUB_OUTPUT
          echo "shard-arg=--shard=$SHARD_INDEX/$TOTAL_SHARDS" >> $GITHUB_OUTPUT
        else
          echo "use-native-sharding=false" >> $GITHUB_OUTPUT
          echo "shard-arg=" >> $GITHUB_OUTPUT
        fi

        echo "grep-pattern=$GREP_PATTERN" >> $GITHUB_OUTPUT
        echo "test-count=$TEST_COUNT" >> $GITHUB_OUTPUT
        echo "expected-duration=$EXPECTED_DURATION" >> $GITHUB_OUTPUT
        echo "is-optimal=$IS_OPTIMAL" >> $GITHUB_OUTPUT

        echo "Assigned $TEST_COUNT tests to shard $SHARD_INDEX (expected: ${EXPECTED_DURATION}ms, optimal: $IS_OPTIMAL)"
