name: Extract Timing Data
description: Extract timing data from Playwright JSON report

inputs:
  report-file:
    description: Path to Playwright JSON report file
    required: true
  output-file:
    description: Path to write timing JSON output
    required: true
  shard:
    description: Shard index for the artifact
    required: true
  project:
    description: Playwright project name
    required: false
    default: 'default'
  level:
    description: Extraction level (file or test)
    required: false
    default: 'test'

outputs:
  test-count:
    description: Number of tests with timing data
    value: ${{ steps.extract.outputs.test-count }}

runs:
  using: composite
  steps:
    - name: Extract timing data
      id: extract
      shell: bash
      run: |
        if [ ! -f "${{ inputs.report-file }}" ]; then
          echo "Report file not found: ${{ inputs.report-file }}"
          echo "test-count=0" >> $GITHUB_OUTPUT
          exit 0
        fi

        npx playwright-orchestrator extract-timing \
          --report-file "${{ inputs.report-file }}" \
          --output-file "${{ inputs.output-file }}" \
          --shard "${{ inputs.shard }}" \
          --project "${{ inputs.project }}" \
          --level "${{ inputs.level }}"

        # Count extracted entries
        if [ "${{ inputs.level }}" = "test" ]; then
          COUNT=$(jq '.tests | length' "${{ inputs.output-file }}")
        else
          COUNT=$(jq '.files | length' "${{ inputs.output-file }}")
        fi

        echo "test-count=$COUNT" >> $GITHUB_OUTPUT
        echo "Extracted timing for $COUNT entries"

    - name: Upload timing artifact
      uses: actions/upload-artifact@v4
      with:
        name: timing-shard-${{ inputs.shard }}
        path: ${{ inputs.output-file }}
        retention-days: 1
