name: Extract Timing Data
description: Extract timing data from Playwright JSON report (storage-agnostic)

inputs:
  report-file:
    description: Path to Playwright JSON report file
    required: true
  output-file:
    description: Path to write timing JSON output
    required: true
  shard:
    description: Shard index for the artifact
    required: true
  project:
    description: Playwright project name
    required: true

outputs:
  test-count:
    description: Number of tests with timing data extracted
    value: ${{ steps.extract.outputs.test-count }}
  success:
    description: Whether extraction succeeded
    value: ${{ steps.extract.outputs.success }}

runs:
  using: composite
  steps:
    - name: Extract timing data
      id: extract
      shell: bash
      run: |
        if [ ! -f "${{ inputs.report-file }}" ]; then
          echo "::warning::Report file not found: ${{ inputs.report-file }}"
          echo "test-count=0" >> $GITHUB_OUTPUT
          echo "success=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        set +e
        playwright-orchestrator extract-timing \
          --report-file "${{ inputs.report-file }}" \
          --output-file "${{ inputs.output-file }}" \
          --shard "${{ inputs.shard }}" \
          --project "${{ inputs.project }}"
        EXIT_CODE=$?
        set -e

        if [ $EXIT_CODE -ne 0 ]; then
          echo "::warning::Failed to extract timing data"
          echo "test-count=0" >> $GITHUB_OUTPUT
          echo "success=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Count extracted tests
        COUNT=$(jq '.tests | length' "${{ inputs.output-file }}" 2>/dev/null || echo "0")

        echo "test-count=$COUNT" >> $GITHUB_OUTPUT
        echo "success=true" >> $GITHUB_OUTPUT
        echo "Extracted timing for $COUNT tests from shard ${{ inputs.shard }}"
