/**
 * Playwright Orchestrator Reporter
 *
 * A custom Playwright reporter that filters tests based on a JSON file
 * containing test IDs. Uses exact Set.has() matching to avoid substring
 * collisions that plague --grep approaches.
 *
 * Usage:
 * 1. Copy this file to your project
 * 2. Add to playwright.config.ts:
 *    reporter: [['./reporter.ts'], ['html']]
 * 3. Set ORCHESTRATOR_SHARD_FILE env var to path of JSON file with test IDs
 *
 * Environment variables:
 * - ORCHESTRATOR_SHARD_FILE: Path to JSON file with array of test IDs
 * - ORCHESTRATOR_DEBUG: Set to "1" to enable debug logging
 *
 * @example
 * // shard.json
 * ["e2e/login.spec.ts::Login::should login", "e2e/home.spec.ts::Home::should render"]
 *
 * // Run with filtering
 * ORCHESTRATOR_SHARD_FILE=shard.json npx playwright test
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import type {
  FullConfig,
  Reporter,
  Suite,
  TestCase,
} from '@playwright/test/reporter';

export default class OrchestratorReporter implements Reporter {
  private allowedTestIds: Set<string> | null = null;
  private debug = process.env.ORCHESTRATOR_DEBUG === '1';

  onBegin(_config: FullConfig, _suite: Suite) {
    const shardFile = process.env.ORCHESTRATOR_SHARD_FILE;

    if (!shardFile || !fs.existsSync(shardFile)) {
      if (this.debug) {
        console.log('[Orchestrator] No shard file, running all tests');
      }
      return;
    }

    try {
      const testIds = JSON.parse(fs.readFileSync(shardFile, 'utf-8'));
      this.allowedTestIds = new Set(testIds);
      console.log(
        `[Orchestrator] ${this.allowedTestIds.size} tests for this shard`,
      );
    } catch (error) {
      console.error('[Orchestrator] Failed to load shard file:', error);
      throw error;
    }
  }

  onTestBegin(test: TestCase) {
    if (!this.allowedTestIds) return;

    const testId = this.buildTestId(test);

    if (!this.allowedTestIds.has(testId)) {
      test.annotations.push({ type: 'skip', description: 'Not in shard' });
      if (this.debug) {
        console.log(`[Skip] ${testId}`);
      }
    }
  }

  /**
   * Build test ID from TestCase.
   * Format: {relative-file}::{describe}::{test-title}
   *
   * This must match the format generated by the orchestrator.
   *
   * Note: titlePath() returns [projectName?, fileName, ...describes, testTitle]
   * We need to filter out projectName and fileName since we already have
   * the full relative file path.
   */
  private buildTestId(test: TestCase): string {
    const file = path
      .relative(process.cwd(), test.location.file)
      .replace(/\\/g, '/');
    const fileName = path.basename(test.location.file);

    // Filter titlePath to exclude project name, filename, and empty strings
    // titlePath typically starts with [projectName, fileName, ...describes, testTitle]
    const titlePath = test.titlePath();
    const projectName = test.parent?.project()?.name;
    const filteredTitles = titlePath.filter((title) => {
      // Skip empty strings
      if (!title || title === '') return false;
      // Skip if it's the project name
      if (title === projectName) return false;
      // Skip if it matches the filename
      if (title === fileName) return false;
      return true;
    });

    return [file, ...filteredTitles].join('::');
  }
}
